# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
#[Info]
site_name: Lenny's Web
site_url: https://lennychen.top/
site_author: Lenny Chen
#[UI]
theme:
  name: material
  custom_dir: docs/overrides
  # custom_dir: material/.overrides
  # font:
  #   text: Bitter
  #   code: Roboto Mono
  logo: https://s2.loli.net/2024/03/31/Ht3QBqhgLYNAuwj.png

  favicon: https://s2.loli.net/2024/03/31/Ht3QBqhgLYNAuwj.png
  # img/11.ico
  palette:
    #primary: blue grey
    - media: "(prefers-color-scheme: light)"
      scheme: default # æ—¥é—´æ¨¡å¼
      primary: deep purple # ä¸Šæ–¹çš„
      accent: indigo # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      # teal
      toggle:
        icon: material/toggle-switch # å›¾æ ‡
        name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # å¤œé—´æ¨¡å¼
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼
  features:
    - announce.dismiss #å‘ˆç°å¯æ ‡è®°ä¸ºç”±ç”¨æˆ·è¯»å–çš„ä¸´æ—¶å…¬å‘Šï¼Œå¯ä»¥åŒ…å«ä¸€ä¸ªç”¨äºå–æ¶ˆå½“å‰å…¬å‘Šçš„æŒ‰é’®
    # - navigation.instant
    #- header.autohide  #è‡ªåŠ¨éšè—
    - navigation.tracking #åœ°å€æ ä¸­çš„ URL å°†è‡ªåŠ¨æ›´æ–°ä¸ºåœ¨ç›®å½•ä¸­çªå‡ºæ˜¾ç¤ºçš„æ´»åŠ¨é”šç‚¹
    - navigation.tabs #é¡¶çº§éƒ¨åˆ†å°†å‘ˆç°åœ¨ä¸Šé¢è§†å£æ ‡é¢˜ä¸‹æ–¹çš„èœå•å±‚ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    # - navigation.tabs.sticky  #å¯ç”¨ç²˜æ€§é€‰é¡¹å¡åï¼Œå¯¼èˆªé€‰é¡¹å¡å°†é”å®šåœ¨æ ‡é¢˜ä¸‹æ–¹ï¼Œå¹¶åœ¨å‘ä¸‹æ»šåŠ¨æ—¶å§‹ç»ˆä¿æŒå¯è§
    - navigation.sections #å¯ç”¨éƒ¨åˆ†åï¼Œé¡¶çº§éƒ¨åˆ†åœ¨è¾¹æ ä¸­å‘ˆç°ä¸º1220pxä»¥ä¸Šè§†å£çš„ç»„ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.footer #é¡µè„šå°†å‘ˆç°åœ¨è¾¹æ ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - navigation.path
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
    - search.share #æœç´¢åˆ†äº«æŒ‰é’®
    # - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - navigation.indexes #å¯ç”¨èŠ‚ç´¢å¼•é¡µåï¼Œå¯ä»¥å°†æ–‡æ¡£ç›´æ¥é™„åŠ åˆ°èŠ‚
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  icon:
    repo: fontawesome/brands/github #å³ä¸Šè§’å›¾æ ‡

edit_uri: edit/main/docs # ç¼–è¾‘æŒ‰é’®è·³è½¬çš„é“¾æ¥
repo_url: https://github.com/LennyChenLaw/LennyChenLaw.github.io # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: LennyChenLaw.github.io # å³ä¸Šè§’çš„åå­—

# [Navigtion]
nav:
  - ğŸ¡ä¸»é¡µ:
      - index.md
      - foreword.md
  - ğŸ’»æŠ€æœ¯:
      - Tech/index.md
      - Tech/Techindex.md
      - ğŸ—ºï¸æˆé•¿è·¯çº¿: Tech/Roadmap/Roadmap.md
      - ğŸ“Šæ•°æ®ç§‘å­¦:
          - Tech/DataScience/index.md
          - MySQL: Tech/DataScience/MySQL.md
          - Excel: Tech/DataScience/Excel.md
          - Tableau: Tech/DataScience/Tableau.md
          - å¤§æ•°æ®æŠ€æœ¯:
              - Hadoop: Tech/DataScience/Frameworks/Hadoop.md
              - Spark: Tech/DataScience/Frameworks/Spark.md
      - ğŸ®Game Dev:
          - Tech/GameDev/index.md
          - Lua: Tech/GameDev/Lua.md
          - Pygame: Tech/GameDev/Pygame.md
          - Unity: Tech/GameDev/Unity.md
          - Godot: Tech/GameDev/Godot.md

      - ğŸ”—æ‚é¡¹:
          - Tech/ToolsWebsites/index.md
          - AIç›¸å…³çš„å·¥å…·: Tech/ToolsWebsites/AI.md
          - PDFå†…åµŒè§†é¢‘: Tech/ToolsWebsites/PDFInsertVideo.md
          - ç½‘ç«™åˆ†äº«: Tech/ToolsWebsites/UsefulWebsites.md
          - MacOS VM on Windows: Tech/ToolsWebsites/VmwareMacOS.md
          - Leetcode: Tech/ToolsWebsites/Leetcode.md
          - LaTeX: Tech/ToolsWebsites/LaTeX.md
          - Ollama: Tech/ToolsWebsites/ollama.md

  - ğŸ“°å‘¨åˆŠ:
      - ğŸ‰2024å¹´:
          - Weekly/Weeklyindex.md
          - Weekly/Week01.md
          - Weekly/Week02.md
          - Weekly/Week03.md
          - Weekly/Week04.md
          - Weekly/Week05.md
          - Weekly/Week06.md
          - Weekly/Week07.md
          - Weekly/Week08.md
          - Weekly/Week09.md
          - Weekly/Week10.md
          - Weekly/Week11.md
          - Weekly/Week12.md
          - Weekly/Week13.md
          - Weekly/Week14.md
          - Weekly/Week15.md

  - ğŸ‡è¯—ä¸è¿œæ–¹:
      - Dream/index.md
      - ğŸˆè‡´å››å¹´å‰çš„ä½ :
          - Dream/ToOldDaysMyself/index.md
          # - Dream/ToOldDaysMyself/ToOldDaysMyselfindex.md
          - ç™½éç«‹ä¸Šè¿›è®°: Dream/ToOldDaysMyself/Vain.md
        # - ä½ æ²¡èƒ½æ˜ç™½çš„äº‹: Dream/ToOldDaysMyself/DelusionalMe.md
        # - æ•¢é—®è·¯åœ¨ä½•æ–¹: Dream/ToOldDaysMyself/WhereShouldIGo.md
        # - è·¯åœ¨è„šä¸‹: Dream/ToOldDaysMyself/Path.md
      - ğŸ§©å‘¨å¤ç›˜:
          - Dream/WeeklyReview/index.md
          # - Dream/WeeklyReview/WeeklyReviewindex.md
          - 2024å¹´:
              - Dream/WeeklyReview/2024/Week1To17.md
              - Dream/WeeklyReview/2024/Week18.md
              - Dream/WeeklyReview/2024/Week19.md
              - Dream/WeeklyReview/2024/Week20.md
              - Dream/WeeklyReview/2024/Week21.md
              - Dream/WeeklyReview/2024/Week22.md

      - ğŸ“šè¯»ä¹¦:
          - ğŸ“šä¹¦ç±: Dream/Books/index.md
          - ğŸ“”å“²å­¦:
              - æ‚é¡¹: Dream/Books/Philosophy/GeneralPhilosophy.md
              - ä¼¦ç†å­¦: Dream/Books/Philosophy/Ethics.md
              - å½¢è€Œä¸Šå­¦: Dream/Books/Philosophy/Metaphysics.md
              - è®¤è¯†è®º: Dream/Books/Philosophy/Epistemology.md
              - ç¾å­¦: Dream/Books/Philosophy/Aesthetics.md
              - é€»è¾‘å­¦: Dream/Books/Philosophy/Logic.md
          - ğŸ“•æ³•å¾‹:
              - å›½å†…æ³•:
                  - å®ªæ³•: Dream/Books/Law/PRCLaw/Constitution.md
                  - åˆ‘æ³•: Dream/Books/Law/PRCLaw/CriminalLaw.md
                  - æ°‘æ³•: Dream/Books/Law/PRCLaw/CivilLaw.md
                  - è¡Œæ”¿æ³•: Dream/Books/Law/PRCLaw/AdministrativeLaw.md
                  - å•†æ³•: Dream/Books/Law/PRCLaw/CommercialLaw.md
                  - åŠ³åŠ¨æ³•: Dream/Books/Law/PRCLaw/LaborLaw.md
                  - çŸ¥è¯†äº§æƒæ³•: Dream/Books/Law/PRCLaw/IntellectualPropertyLaw.md
              - å›½é™…æ³•:
                  - å›½é™…å…¬æ³•: Dream/Books/Law/InternationalLaw/InternationalPublicLaw.md
                  - å›½é™…ç§æ³•: Dream/Books/Law/InternationalLaw/InternationalPrivateLaw.md
                  - å›½é™…äººæƒæ³•: Dream/Books/Law/InternationalLaw/InternationalHumanRightsLaw.md
                  - å›½é™…ç»æµæ³•: Dream/Books/InternationalLaw/InternationalEconomicLaw.md
          - ğŸ“—æ–‡å­¦:
              - äºšæ´²æ–‡å­¦:
                  - China: Dream/Books/Literature/Asia/China/China.md
                  - Japan: Dream/Books/Literature/Asia/Japan/Japan.md
              - åŒ—ç¾æ–‡å­¦: Dream/Books/Literature/NA/NorthAmerica.md
              - æ‹‰ä¸ç¾æ´²æ–‡å­¦: Dream/Books/Literature/LA/LatinAmerica.md
              - æ¬§æ´²æ–‡å­¦: Dream/Books/Literature/Europe/Europe.md
          - ğŸ“™å¿ƒç†å­¦: Dream/Books/Psychology/Psychology.md
          - ğŸ“˜å°è¯´:
              - å†å²å°è¯´: Dream/Books/Fiction/HistoricalFiction.md
              - ç§‘å¹»å°è¯´: Dream/Books/Fiction/ScienceFiction.md
              - æ¨ç†å°è¯´: Dream/Books/Fiction/DetectiveFiction.md
              - æ­¦ä¾ å°è¯´: Dream/Books/Fiction/MartialArtsFiction.md
      - âœ’ï¸éšç¬”:
          - é“å¾·: Dream/Thoughts/é“å¾·.md
          - å†™ç‚¹ä¸œè¥¿: Dream/Thoughts/å†™ç‚¹ä¸œè¥¿.md
          - å­¤ç‹¬: Dream/Thoughts/å­¤ç‹¬.md
      - â›°ï¸æ—…è¡Œ: Dream/Travel/Travel.md
      - ğŸ•¹ï¸æ¸¸æˆ: Dream/Games/Games.md
      - ğŸ“ºåŠ¨æ¼«:
          - Dream/AnimeManga/index.md
          - åŠ¨ç”»:
              - ä¸­å›½åŠ¨ç”»:
                  - TVåŠ¨ç”»ğŸ‡¨ğŸ‡³: Dream/AnimeManga/Anime/China/ChineseAnime.md
                  - åŠ¨ç”»ç”µå½±ğŸ‡¨ğŸ‡³: Dream/AnimeManga/Anime/China/ChineseAnimeMovie.md
              - æ—¥æœ¬åŠ¨ç”»:
                  - TVåŠ¨ç”»ğŸ‡¯ğŸ‡µ: Dream/AnimeManga/Anime/Japan/JapaneseAnime.md
                  - åŠ¨ç”»ç”µå½±ğŸ‡¯ğŸ‡µ: Dream/AnimeManga/Anime/Japan/JapaneseAnimeMovie.md
              - æ¬§ç¾åŠ¨ç”»:
                  - TVåŠ¨ç”»: Dream/AnimeManga/Anime/EuroAndAmerica/EuroAndAmericaAnime.md
                  - åŠ¨ç”»ç”µå½±: Dream/AnimeManga/Anime/EuroAndAmerica/EuroAndAmericaAnimeMovie.md
              - çŸ­ç‰‡åŠ¨ç”»: Dream/AnimeManga/Anime/ShortAnimation/ShortAnimation.md
          - æ¼«ç”»:
              - ä¸­å›½æ¼«ç”»: Dream/AnimeManga/Manga/ChinaManhwa/ChinaManhwa.md
              - æ—¥æœ¬æ¼«ç”»: Dream/AnimeManga/Manga/JapanManga/JapanManga.md
      - ğŸ’ªå¥èº«:
          - Dream/Bodybuilding/index.md
          - Dream/Bodybuilding/Bodybuilding.md
          - Dream/Bodybuilding/EarlyNotes.md
      - ğŸ‘¨â€ğŸ“è€ƒç ”: Dream/Master/Master.md
      - ğŸ‘¨â€âš–ï¸å·¥ä½œ: Dream/Work/Work.md

  # `éšç¬”`ã€`æ­¤åˆ»æ„Ÿå—`ã€`è¯­è¨€`ã€`å­¦ä¹ ç¬”è®°`ç­‰å·²ç»ä»`è¯—ä¸è¿œæ–¹`sectioné‡Œè„±ç¦»å‡ºæ¥ï¼Œæˆä¸ºç‹¬ç«‹çš„sectionï¼Œä½†æ–‡ä»¶å¤¹è¿˜æ˜¯åœ¨Dreamä¸‹ï¼Œå› ä¸ºä¿®æ”¹èµ·æ¥å¤ªéº»çƒ¦ï¼Œç°åœ¨å…ˆä¸ç®¡ï¼Œç­‰ä¹‹åæ‰¾ä¸ªæ—¶é—´æ”¹å§

  - ğŸ’­æ­¤åˆ»æ„Ÿå—: Dream/Moments/Moments.md
  - ğŸŒè¯­è¨€:
      - Dream/Languages/index.md
      - Dream/Languages/Languagesindex.md
      - è‹±è¯­: Dream/Languages/English.md
      - æ—¥è¯­: Dream/Languages/Japanese.md
      - å¾·è¯­: Dream/Languages/German.md

  - ğŸ“„å­¦ä¹ ç¬”è®°:
      - Dream/Notes/index.md
      - ğŸ·ï¸Foreword: Dream/Notes/NotesForeword.md
      - ğŸ·ï¸Crash Course:
          - Dream/Notes/CrashCourse/index.md
          - World History:
              - Dream/Notes/CrashCourse/WorldHistory/WorldHistoryindex.md
              - Dream/Notes/CrashCourse/WorldHistory/WorldHistory1.md
          - Philosophy:
              - Dream/Notes/CrashCourse/Philosophy/Philosophyindex.md
              - Dream/Notes/CrashCourse/Philosophy/Philosophy1.md
          - Biology:
              - Dream/Notes/CrashCourse/Biology/Biologyindex.md
              - Dream/Notes/CrashCourse/Biology/Biology1.md
              - Dream/Notes/CrashCourse/Biology/Biology37.md
          - Psychology:
              - Dream/Notes/CrashCourse/Psychology/Psychologyindex.md
              - Dream/Notes/CrashCourse/Psychology/Psychology1.md
      - ğŸ·ï¸edX:
          - Dream/Notes/edX/index.md
          - CS50's Introduction to Computer Science: Dream/Notes/edX/CS50.md
          - How To Write An Essay: Dream/Notes/edX/HowToWriteAnEssay.md
      - ğŸ·ï¸MITOpenCourseWare:
          - Dream/Notes/MITOpenCourseWare/index.md
          - Linear Algebra 18.06: Dream/Notes/MITOpenCourseWare/LinearAlgebra18.06.md
          - Philosophy Of Law: Dream/Notes/MITOpenCourseWare/PhilosophyOfLaw24.235J.md
      - ğŸ·ï¸FreeCodeCamp:
          - Dream/Notes/FreeCodeCamp/index.md
          - HTML and CSS Tutorials:
              - Learn HTML & CSS â€“ Full Course for Beginners: Dream/Notes/FreeCodeCamp/HTMLCSS/FullCourse.md
              - CSS Tutorial - Zero to Hero (Complete Course): Dream/Notes/FreeCodeCamp/HTMLCSS/CSSZeroToHero.md
          - JavaScript Tutorials:
              - Build 15 JavaScript Projects - Vanilla JavaScript Course: Dream/Notes/FreeCodeCamp/VanillaJavaScript.md
          - Python:
              - Python for Data Science - Course for Beginners (Learn Python, Pandas, NumPy, Matplotlib): Dream/Notes/FreeCodeCamp/Python/PandasNumpyMatplotlib.md
              - Object Oriented Programming with Python - Full Course for Beginners: Dream/Notes/FreeCodeCamp/Python/OOP.md
      - ğŸ·ï¸Coursera:
          - Dream/Notes/Coursera/index.md
          - Computer Orgnization: Dream/Notes/Coursera/ComputerOrganization.md
      - ğŸ·ï¸Others:
          - Dream/Notes/Others/index.md
          - CSExceptMOOC:
              - Dream/Notes/Others/CSExceptMOOC/CSEMindex.md
              - Dream/Notes/Others/CSExceptMOOC/HowDoComputersReadCode.md
              - Dream/Notes/Others/CSExceptMOOC/TheMissingSemester.md
          - PsychologyExceptMOOC:
              - Dream/Notes/Others/PsychologyExceptMOOC/PEMindex.md
              - Dream/Notes/Others/PsychologyExceptMOOC/SisyphusDoYouWantToBeLoved.md
              - Dream/Notes/Others/PsychologyExceptMOOC/SisyphusTheMythofProductivity.md

  - ğŸ“œè®ºæ–‡é˜…è¯»: Thesis/Thesisindex.md
  - ğŸ”–æ ‡ç­¾: tag.md
  - ğŸ™†â€â™‚ï¸å…³äº:
      - about/index.md
      - ä¸ªäººç®€ä»‹: about/profile.md
      # - ç®€å†: about/LennyResume.pdf
      - æƒ³åšçš„äº‹: about/goal.md
      - Github: about/GithubProfile.md
      - æ”¯æŒä½œè€…: about/sponsor.md

  - ğŸ“§äº’åŠ¨:
      - Interaction/index.md
      - å‹é“¾: Interaction/links.md
      - ç•™è¨€æ¿: Interaction/Comment.md
      - æ›´æ–°æ—¥å¿—: Interaction/log.md

copyright: Copyright &copy; 2022~2024 Lenny/All Rights Reserved. # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜

extra:
  # tags:
  #   HTML5: html
  #   JavaScript: js
  #   CSS: css
  # alternate:
  #   - name: English
  #     link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #     lang: en
  #   - name: ä¸­å›½(å°æ¹¾)
  #     link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=zh-TW&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #     lang: zh-TW
  generator: true #åˆ é™¤é¡µè„šæ˜¾ç¤ºâ€œä½¿ç”¨ MkDocs ææ–™åˆ¶é€ â€
  social:
    - icon: fontawesome/brands/weixin
      link: https://s2.loli.net/2024/03/30/kHBUML1XdERzljK.jpg
      name: weixin
    # - icon: fontawesome/brands/x-twitter
    #   link: https://twitter.com/wcowin_
    #   name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/LennyChenLaw
      name: Github
    - icon: fontawesome/regular/envelope
      link: mailto:<lennychenlaw@gmail.com> #è”ç³»æ–¹å¼
      name: Email

  analytics:
    provider: google
    property: G-29HZMNR0KG
    feedback:
      title: æ­¤é¡µé¢æœ‰å¸®åŠ©å—ï¼Ÿ
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            è°¢è°¢ä½ çš„åé¦ˆï¼
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.

  # consent:
  #   title: Cookie consent
  #   description: >-
  #     æˆ‘ä»¬ä¹Ÿä½¿ç”¨cookiesæ¥è¯†åˆ«æ‚¨çš„é‡å¤è®¿é—®å’Œåå¥½æ¥è¡¡é‡æˆ‘ä»¬æ–‡æ¡£çš„æœ‰æ•ˆæ€§ä»¥åŠç”¨æˆ·æ˜¯å¦æ‰¾åˆ°ä»–ä»¬è¦æ‰¾çš„ä¸œè¥¿ã€‚
  #     å¦‚æœä½ åŒæ„,ä½ å¯ä»¥å¸®åŠ©æˆ‘ä»¬è®©æˆ‘ä»¬çš„ç½‘ç«™æ›´å¥½

plugins:
  # - glightbox
  - search
  - offline
  - statistics:
      words_per_minute: 200
      page_check_metadata: tags
  - git-revision-date-localized:
      type: iso_date
      enable_creation_date: false
      exclude:
        - index.md
        - tag.md
        - Comment.md
        # - blog/posts/update.md
        # - blog/posts/wkw.md
        - about/links.md
  - git-committers:
      enabled: !ENV [CI, false]
      repository: LennyChenLaw/LennyChenLaw.github.io
      branch: main
      exclude:
        - index.md
        - Interaction/links.md
  # - git-authors:
  #     exclude:
  #       - index.md

  # ===æœ‰ç‚¹åƒæ›´æ–°æ—¥å¿—ï¼Œæˆ‘å…ˆæ³¨é‡Šæ‰äº†
  - blog:
      post_date_format: full #æ—¶é—´
      draft: true
      draft_if_future_date: true #è‡ªåŠ¨å°†å…·æœ‰æœªæ¥æ—¥æœŸçš„å¸–å­æ ‡è®°ä¸ºè‰ç¨¿
      post_readtime: true
      post_readtime_words_per_minute: 265 #è®¡ç®—å¸–å­çš„é˜…è¯»æ—¶é—´æ—¶è¯»è€…æ¯åˆ†é’Ÿé¢„è®¡é˜…è¯»çš„å­—æ•°
      post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # categories_toc: true
      # pagination_per_page: 5
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml" #ä½œè€…ä¿¡æ¯
  - tags:
      tags_file: tag.md #åˆ†ç±»æ ‡ç­¾

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - markdown.extensions.abbr # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex: # latexæ”¯æŒ
      generic: true
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      anchor_linenums: true
      linenums: true # æ˜¾ç¤ºè¡Œå·
      # auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

extra_javascript:
  - javascripts/extra.js
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extraçš„cdn
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - javascripts/mathjax-config.js
  # - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML

  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  # - ckplayer/js/ckplayer.js
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/js/social-share.min.js
  # - javascripts/backbound1.js
  # - javascripts/rellax.min.js
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js
  # - https://res.zvo.cn/translate/translate.js  # Translate

extra_css:
  - stylesheets/extra.css
  # - stylesheets/extra1.css
  - stylesheets/extra2.css
  - stylesheets/link.css
  - stylesheets/customize.css
  # - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/stylesheets/extra.css # extra.cssçš„CDN
  # - stylesheets/extra1.css
  # - stylesheets/video.css
  # - https://unpkg.com/@waline/client@v2/dist/waline.css
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #è¯„è®º
  # - ckplayer/css/ckplayer.css
  # - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css #å­—ä½“

